version: 0.2

phases:
  pre_build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${CONTAINER_REGISTRY}
      - echo "WEBHOOK=${WEBHOOK}"
      - if [ "$WEBHOOK" = "true" ]; then BRANCH=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | awk -F/ '{print $NF}'); fi
      - echo "BRANCH=${BRANCH}"
      - TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "TAG=${TAG}"
    finally:
      - cd docker
  build:
    on-failure: ABORT
    commands:
      - ./build.sh all -t prod -r ${CONTAINER_REGISTRY} -b ${CONTAINER_REGISTRY}
      - ./build.sh all -t dev -r ${CONTAINER_REGISTRY} -b ${CONTAINER_REGISTRY} -c
      - docker image ls
    finally:
      - ./build-report.py -p build
  post_build:
    commands:
      - docker push ${CONTAINER_REGISTRY}/nginx:prod
      - docker push ${CONTAINER_REGISTRY}/db-nextjs:prod
      - docker push ${CONTAINER_REGISTRY}/db-strapi:prod
      - docker push ${CONTAINER_REGISTRY}/nextjs-app:prod
      - docker push ${CONTAINER_REGISTRY}/strapi:prod
      - docker push ${CONTAINER_REGISTRY}/nginx:dev 
      - docker push ${CONTAINER_REGISTRY}/db-nextjs:dev
      - docker push ${CONTAINER_REGISTRY}/db-strapi:dev
      - docker push ${CONTAINER_REGISTRY}/nextjs-app:dev
      - docker push ${CONTAINER_REGISTRY}/strapi:dev
    finally:
      - ./build-report.py -p post_build
